# Site settings
title: The Adamant Programming Language
email: site-admin@adamant-lang.org
description: > # this means to ignore newlines until "baseurl:"
  Adamant will be a general-purpose language with high performance,
  deterministic safe resource management, and guaranteed thread safety.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adamant-lang.org" # the base hostname & protocol for your site
twitter_username: AdamantLang
github_username:  adamant
encoding: UTF-8
repository: adamant/adamant-lang.org

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true # disable syntax hilighting server side
incremental: false # still experimental and seems to be causeing problems
strict_front_matter: true

# Exclude from processing.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
