# Site settings
title: The Adamant Programming Language
email: site-admin@adamant-lang.org
description: > # this means to ignore newlines until "baseurl:"
  Adamant will be a general-purpose language with high performance,
  deterministic safe resource management, and guaranteed thread safety.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adamant-lang.org" # the base hostname & protocol for your site
twitter_username: AdamantLang
github_username:  adamant
encoding: UTF-8
permalink: /blog/:year/:title
paginate: 5
paginate_path: "/blog/page:num"
repository: adamant/adamant.org

# Build settings
markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
